services:
  web:
    image: xboard:ez
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.data
      - ./storage/theme:/www/storage/theme
      - ./storage/logs:/www/storage/logs
      - ./plugins:/www/plugins
    environment:
      - docker=true
    command: php artisan octane:start --port=7001 --host=0.0.0.0
    restart: always
    network_mode: host

  horizon:
    image: xboard:ez
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.data
      - ./storage/logs:/www/storage/logs
      - ./plugins:/www/plugins
    restart: always
    command: php artisan horizon
    network_mode: host

