services:
  web:
    image: xboard:local
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.data
      - ./storage/theme:/www/storage/theme
      - ./storage/logs:/www/storage/logs
      - ./plugins:/www/plugins
    environment:
      - docker=true
    depends_on:
      - redis
    command: php artisan octane:start --port=7001 --host=0.0.0.0
    restart: always
    networks:
      - xboard-network

  horizon:
    image: xboard:local
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.data
      - ./storage/logs:/www/storage/logs
      - ./plugins:/www/plugins
    restart: always
    depends_on:
      - redis
    command: php artisan horizon
    networks:
      - xboard-network

  redis:
    image: redis:7-alpine
    command: redis-server --unixsocket /data/redis.sock --unixsocketperm 777 --save 900 1 --save 300 10 --save 60 10000
    restart: unless-stopped
    volumes:
      - ./.docker/.data/redis:/data
    networks:
      - xboard-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/logs:/var/log/nginx
      - ./.docker/nginx/certs:/etc/nginx/certs:ro
      - ./.docker/nginx/html:/etc/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - xboard-network

networks:
  xboard-network:
    driver: bridge
