services:
  web:
    image: xboard:local
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data
      - ./storage/logs:/www/storage/logs
      - ./storage/theme:/www/storage/theme
      - ./plugins:/www/plugins
    environment:
      - docker=true
    command: php artisan octane:start --host=0.0.0.0 --port=7001
    restart: on-failure
    ports:
      - 7001:7001
    networks: host

  horizon:
    image: xboard:local
    volumes:
      - ./.docker/.data/redis/:/data/
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data
      - ./storage/logs:/www/storage/logs
      - ./plugins:/www/plugins
    restart: on-failure
    command: php artisan horizon
    networks: host

  openresty:
    image: openresty/openresty:alpine
    volumes:
      - ./.docker/openresty/conf:/usr/local/openresty/nginx/conf:ro
      - ./.docker/openresty/logs:/usr/local/openresty/nginx/logs
    network_mode: host
    restart: unless-stopped
    depends_on:
      - web
